<a href="https://colab.research.google.com/github/satishgunjal/Machine-Learning-Using-Python/blob/master/12_K_Fold_Cross_Validation/Exercise_K_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise

Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

* Logistic Regression
* SVM
* Decision Tree
* Random Forest

Import required liabraries

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.datasets import load_iris


In [7]:
iris = load_iris()
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

## Understanding the IRIS dataset
* iris.DESCR > Complete description of dataset
* iris.data > Data to learn. Each training set is 4 digit array of features. Total 150 training sets
* iris.feature_names > Array of all 4 feature ['sepal length (cm)','sepal width cm)','petal length (cm)','petal width (cm)']
* iris.filename > CSV file name
* iris.target > The classification label. For every training set there is one classification label(0,1,2). Here 0 for setosa, 1 for versicolor and 2 for virginica
* iris.target_names > the meaning of the features. Its a array >> ['setosa', 'versicolor', 'virginica']
* From above details its clear that our data is 'iris.data' and labels are 'iris.target'

### Lets test teh LogisticRegression model performance using cross_val_score

In [15]:
score_lr = cross_val_score(LogisticRegression(solver='liblinear'), iris.data, iris.target,cv=3)
print(score_lr)
print('average score %s' % (np.average(score_lr)))

[0.96 0.96 0.94]
average score 0.9533333333333333


### Lets test the SVM model performance using cross_val_score

In [16]:
score_svc = cross_val_score(SVC(),iris.data,iris.target,cv=3)
print(score_svc)
print('average score %s' % (np.average(score_svc)))

[0.96 0.98 0.94]
average score 0.96


Lets test the Decision Tree model performance using cross_val_score

In [17]:
score_dt = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)
print(score_dt)
print('average score %s' % (np.average(score_dt)))

[0.98 0.92 0.98]
average score 0.96


Lets test the RandomForest models performance using cross_val_score

In [18]:
score_rf = cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=3)
print(score_rf)
print('average score %s' % (np.average(score_rf)))

[0.98 0.94 0.98]
average score 0.9666666666666667
