<a href="https://colab.research.google.com/github/satishgunjal/Machine-Learning-Using-Python/blob/master/01_Linear_Regression/Linear_Regression_Multi_Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Linear Regression With Multiple Variables
[Reference](ML/2_linear_reg_multivariate/2_linear_regression_multivariate.ipynb)

Predict prices of new homes based on area, bed rooms and age                      
Q1: 3000 sqr ft area, 3 bedrooms, 40 year old                                      
Q2: 2500 sqr ft area, 4 bedrooms, 5 year old

In [0]:
import pandas as pd
import numpy as np
from sklearn import linear_model

Below code will work if Jupytor is running locally and all the files are on local systym

In [0]:
#df = pd.read_csv('homeprices_multivariate.csv')
#df

Upload the file 

In [2]:
from google.colab import files

uploaded = files.upload()

Saving homeprices_multivariate.csv to homeprices_multivariate.csv


'uploaded' is a dictionary object with file name as key and contect as value. Lets use pandas to load the file content into dataframe

In [6]:
import io
df = pd.read_csv(io.StringIO(uploaded['homeprices_multivariate.csv'].decode('utf-8')))
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

As youi can see from data, we must replace 'NaN' with median value of that column

In [9]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
# OR you can use below syntax with 'inplace = True' >> It will replace the value and update the dataframe
df.bedrooms.fillna(df.bedrooms.median(),inplace=True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

Now lets train the model using linear rgression

In [12]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Note the coeffient and intercept values

In [13]:
reg.coef_m

array([  112.06244194, 23388.88007794, -3231.71790863])

In [14]:
reg.intercept_

221323.00186540396

Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

In [18]:
reg.predict([[3000,3,40]])
# OR
# y = m1*x1 + m2*x2 + m3*x3 + b
#y = 112.06244194*3000 + 23388.88007794*3 + (-3231.71790863*40) + 221323.00186540396
#y

498408.251574024

Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [20]:
reg.predict([[2500,4,5]])
# OR
# y = m1*x1 + m2*x2 + m3*x3 + b
#y = 112.06244194*2500 + 23388.88007794*4 + (-3231.71790863*5) + 221323.00186540396
#y

array([578876.03748933])

#Exercise
The CSV exercise_multivariate_hiring.csv contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates.

**Q1: 2 yr experience, 9 test score, 6 interview score**                            
**Q2: 12 yr experience, 10 test score, 10 interview score**

**Step#1** Load the data in dataframe

In [0]:
# Use this code if you are running Jupytor locally and CSV files are on same PC
#df = pd.read_csv('exercise_multivariate_hiring.csv')
#df

In [98]:
from google.colab import files
uploaded = files.upload()

Saving exercise_multivariate_hiring.csv to exercise_multivariate_hiring (3).csv


In [99]:
e_df = pd.read_csv(io.StringIO(uploaded['exercise_multivariate_hiring.csv'].decode('utf-8')))
e_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

**Step#2:** From data visualization its clear trhat we have to replace 'NaN' for column 'test_score(out of 10)' with median value. ANd for column 'experience' replace 'NaN' with 0 and convert numbers from word to numeric format

In [100]:
e_df['test_score(out of 10)'] = e_df['test_score(out of 10)'].fillna(math.floor(e_df['test_score(out of 10)'].mean()))
e_df['test_score(out of 10)']
# Note here we are taking mean not median

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     7.0
7     7.0
Name: test_score(out of 10), dtype: float64

In [101]:
e_df.experience = e_df.experience.fillna(0) # here we can even fill 'zero' since we are going to convert all words to numeric
e_df.experience

0         0
1         0
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [102]:
#You can install the module using Python Package Index using the below command
pip install word2number

In [103]:
# Now import the module
from word2number import w2n
#Convert number from word to numeric format

i = 0
for element in e_df.experience:
  e_df.experience[i] = (w2n.word_to_num(str(element)))
  i = i + 1

e_df.experience

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: object

In [104]:
# Final data set will lokks like this
e_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          0                    8.0                           9      50000
1          0                    8.0                           6      45000
2          5                    6.0                           7      60000
3          2                   10.0                          10      65000
4          7                    9.0                           6      70000
5          3                    7.0                          10      62000
6         10                    7.0                           7      72000
7         11                    7.0                           8      80000

**Step#3:** Now lest train the Linear regression model

In [105]:
e_reg = linear_model.LinearRegression()
e_reg.fit(e_df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']],e_df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Step#4: Note the coeffient and intercept

In [106]:
e_reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [107]:
e_reg.intercept_

14992.651446693148

**Step#4:** Prediction: 2 yr experience, 9 test score, 6 interview score

In [108]:
e_reg.predict([[2,9,6]])

array([53713.86677124])

**Step#5**: 12 yr experience, 10 test score, 10 interview score

In [109]:
e_reg.predict([[12,10,10]])

array([93747.79628651])